name: deploy to kubernetes

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '.github/workflows/kubernetes.yaml'
      - 'package.json'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: login to docker
        run: docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build container image
        run: |
          docker build . --tag ghcr.io/trixinity/delagevachtjes/dlv-bot:${{ github.sha }}
          docker image tag ghcr.io/trixinity/delagevachtjes/dlv-bot:${{ github.sha }} ghcr.io/trixinity/delagevachtjes/dlv-bot:latest

      - name: Push image to Docker Hub
        run: |
            docker push ghcr.io/trixinity/delagevachtjes/dlv-bot:${{ github.sha }}
            docker push ghcr.io/trixinity/delagevachtjes/dlv-bot:latest

      - name: Save DigitalOcean kubeconfig
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show k8s-okto > $GITHUB_WORKSPACE/.kubeconfig

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig -n discord-bots set image statefulset/stateful-dlv dlv-bot=ghcr.io/trixinity/delagevachtjes/dlv-bot:${{ github.sha }}
